# Generated by Django 4.2.2 on 2023-06-24 03:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_moderator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFollowedSpaces',
            new_name='UserFollowedSpace',
        ),
    ]
